engines:
  duplication:
    enabled: true
    config:
      languages:
        ruby:
        javascript:
        python:
        php:
          mass_threshold: 20
  phan:
      enabled: true
      config:
        file_extensions: "php"
        ignore-undeclared: true
        dead-code-detection: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
  phpcodesniffer:
    enabled : true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- features/
- spec/
- bin/
- .codeclimate.yml
- .gitignore
- .travis.yml
- composer.json
- composer.lock
- phpspec.yml
- phpspec-ci.yml
- README.md